server:
  port: 8080
logging:
  level:
    root: info
spring:
  boot:
    admin:
      client:
        username: admin
        password: admin
        url: http://localhost:8888
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: zhao19971107A
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime: 1800000
      idle-timeout: 600000
      connection-timeout: 600000
      connection-test-query: SELECT 1
      auto-commit: false
